name: Update NuGet Packages

on:
  schedule:
    - cron: '0 2 * * *'  # Ka¿dego dnia o 2:00 w nocy UTC
  workflow_dispatch:      # Równie¿ manualnie

jobs:
  update-packages:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            8.0.x
            9.0.x

      - name: Install dotnet-outdated tool
        run: dotnet tool install --global dotnet-outdated-tool

      - name: Update packages in Directory.Packages.props
        run: |
          dotnet outdated ./Source/Directory.Packages.props --upgrade --no-restore --output outdated.txt

      - name: Check if something changed
        id: git-check
        run: |
          if [[ -z "$(git status --porcelain)" ]]; then
            echo "No changes to commit"
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "There are changes to commit"
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit changes
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git checkout -b auto/update-nuget-packages
          git add Source/Directory.Packages.props
          git add outdated.txt
          git commit -m "chore: update NuGet packages in Directory.Packages.props"

      - name: Push changes to remote
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git push --set-upstream origin auto/update-nuget-packages

      - name: Create Pull Request
        if: steps.git-check.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: auto/update-nuget-packages
          title: "chore: Update NuGet packages in Directory.Packages.props"
          body: |
            This PR updates NuGet packages in `Directory.Packages.props`.

            **Changelog:**  
            <details>
              <summary>dotnet-outdated output</summary>

              ```
              $(cat outdated.txt)
              ```
            </details>
          labels: |
            auto-update