name: Update NuGet Packages

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  update-packages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Fail if not on master
        if: github.ref != 'refs/heads/master'
        run: |
          echo "This workflow must run only on master branch!"
          exit 1

      - name: Checkout master
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0

      - name: Setup .NET 8 and 9 SDKs
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x

      - name: Install dotnet-outdated tool
        run: dotnet tool install --global dotnet-outdated-tool

      - name: Find solution file
        id: find-sln
        run: |
          slnfile=$(find . -maxdepth 1 -name '*.sln' | head -n 1)
          if [[ -z "$slnfile" ]]; then
            echo "No solution file found!"
            exit 1
          fi
          echo "sln=$slnfile" >> $GITHUB_OUTPUT
          echo "Found solution: $slnfile"

      - name: Update packages using dotnet-outdated (with JSON)
        run: |
          dotnet outdated "${{ steps.find-sln.outputs.sln }}" --upgrade --no-restore --output outdated_result.json --output-format json | tee dotnet_outdated.log

      - name: Check for changes
        id: git-check
        run: |
          if [[ -z "$(git status --porcelain)" ]]; then
            echo "No changes to commit"
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected"
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Generate NuGet update summary markdown
        if: steps.git-check.outputs.changed == 'true'
        run: |
          echo "### NuGet package updates" > nuget_changes.md
          if [ -f outdated_result.json ]; then
            updates=$(jq -r '.projects[].dependencies[] | select(.latest_version != .resolved_version) | "- `" + .name + "`: " + .resolved_version + " → " + .latest_version' outdated_result.json)
            if [ -z "$updates" ]; then
              echo "_No NuGet updates detected._" >> nuget_changes.md
            else
              echo "$updates" >> nuget_changes.md
            fi
          else
            echo "_dotnet outdated did not produce JSON results._" >> nuget_changes.md
          fi

          echo -e "\n<details>\n<summary>dotnet outdated log</summary>\n" >> nuget_changes.md
          echo '```text' >> nuget_changes.md
          cat dotnet_outdated.log >> nuget_changes.md
          echo '```' >> nuget_changes.md
          echo "</details>" >> nuget_changes.md

      - name: Create Pull Request
        if: steps.git-check.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          title: "[Task] Automated NuGet package update"
          commit-message: "[Task] Automated NuGet package update"
          branch: auto/update-nuget-packages
          base: master
          delete-branch: true
          labels: automated-task
          body-path: nuget_changes.md