name: Update NuGet Packages

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  update-packages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Fail if not on master
        if: github.ref != 'refs/heads/master'
        run: |
          echo "This workflow must run only on master branch!"
          exit 1

      - name: Checkout master
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0

      - name: Setup .NET 8 and 9 SDKs
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x

      - name: Install dotnet-outdated tool
        run: dotnet tool install --global dotnet-outdated-tool

      - name: Find solution file
        id: find-sln
        run: |
          slnfile=$(find . -maxdepth 1 -name '*.sln' | head -n 1)
          if [[ -z "$slnfile" ]]; then
            echo "No solution file found!"
            exit 1
          fi
          echo "sln=$slnfile" >> $GITHUB_OUTPUT
          echo "Found solution: $slnfile"

      - name: Update packages using dotnet-outdated
        run: |
          dotnet outdated "${{ steps.find-sln.outputs.sln }}" --upgrade --no-restore | tee dotnet_outdated.log

      - name: Check for changes
        id: git-check
        run: |
          if [[ -z "$(git status --porcelain)" ]]; then
            echo "No changes to commit"
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected"
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Get NuGet diff for PR body (with logs)
        if: steps.git-check.outputs.changed == 'true'
        run: |
          echo "### NuGet package updates" > nuget_changes.md
          found=0
          for prj in $(git diff --name-only | grep -E '\.(csproj|fsproj|vbproj|props)$' || true); do
            pkg_diff=$(git diff "$prj" | grep -E '^[+-].*PackageReference|^[+-].*<PackageVersion' | grep -v 'Include="Microsoft\.NET' || true)
            if [[ -n "$pkg_diff" ]]; then
              found=1
              echo "" >> nuget_changes.md
              echo "**\`$prj\`**" >> nuget_changes.md
              echo '```diff' >> nuget_changes.md
              echo "$pkg_diff" >> nuget_changes.md
              echo '```' >> nuget_changes.md
            fi
          done
          if [ $found -eq 0 ]; then
            echo "_No NuGet changes detected._" >> nuget_changes.md
          fi

          # --- Dodaj logi jako zwijany blok ---
          echo -e "\n<details>\n<summary>dotnet outdated log</summary>\n" >> nuget_changes.md
          echo '```text' >> nuget_changes.md
          cat dotnet_outdated.log >> nuget_changes.md
          echo '```' >> nuget_changes.md
          echo "</details>" >> nuget_changes.md

      - name: Create Pull Request
        if: steps.git-check.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          title: "[Task] Automated NuGet package update"
          commit-message: "[Task] Automated NuGet package update"
          branch: auto/update-nuget-packages
          base: master
          delete-branch: true
          labels: automated-task
          body-path: nuget_changes.md